
import { Property } from './types';

export const PROPERTIES: Property[] = [
  {
    id: 1,
    title: 'Modern Downtown Loft',
    type: 'Rent',
    price: '$3,500/mo',
    location: 'Austin, TX',
    beds: 2,
    baths: 2,
    sqft: 1200,
    imageUrl: 'https://picsum.photos/seed/house1/400/300',
  },
  {
    id: 2,
    title: 'Suburban Family Home',
    type: 'Buy',
    price: '$650,000',
    location: 'Plano, TX',
    beds: 4,
    baths: 3,
    sqft: 2800,
    imageUrl: 'https://picsum.photos/seed/house2/400/300',
  },
  {
    id: 3,
    title: 'Luxury Beachfront Villa',
    type: 'Buy',
    price: '$2,800,000',
    location: 'Miami, FL',
    beds: 5,
    baths: 5,
    sqft: 5500,
    imageUrl: 'https://picsum.photos/seed/house3/400/300',
  },
  {
    id: 4,
    title: 'Cozy City Apartment',
    type: 'Rent',
    price: '$2,100/mo',
    location: 'New York, NY',
    beds: 1,
    baths: 1,
    sqft: 750,
    imageUrl: 'https://picsum.photos/seed/house4/400/300',
  },
    {
    id: 5,
    title: 'Mountain View Cabin',
    type: 'Buy',
    price: '$475,000',
    location: 'Denver, CO',
    beds: 3,
    baths: 2,
    sqft: 1800,
    imageUrl: 'https://picsum.photos/seed/house5/400/300',
  },
  {
    id: 6,
    title: 'Chic Urban Condo',
    type: 'Rent',
    price: '$4,200/mo',
    location: 'San Francisco, CA',
    beds: 2,
    baths: 2,
    sqft: 1100,
    imageUrl: 'https://picsum.photos/seed/house6/400/300',
  },
];
